version: '3.11'
services:
    
  web:
    build: .
    network_mode: "host"  # Critical for OCI compatibility
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    # Remove ports: - "8501:8501" (redundant with host mode)