version: '3.11'
services:
  web:
    build: .
    network_mode: "host"  # Critical for OCI compatibility
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=89.168.104.162
    restart: unless-stopped
